import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import { compileDeclarativeScenario, predicateExpression } from './data-compiler.mjs';

const base = (predicate, action = { type: 'wait', target: 'field' }) => ({
  schema_version: 1,
  scenario_id: 'data-test',
  inputs: { expected: 'Smoke', url: 'https://fixture.test/' },
  targets: { field: { selector: '#field' } },
  flows: {
    simple: {
      flow_id: 'data-test', revision: 1, timeout_ms: 5000,
      checks: { ready: { predicate, timeout_ms: 100, poll_ms: 5, stable_ms: 0 } },
      steps: [{ id: 'open', label: 'Open', timeout_ms: 1000, action, expect: ['ready'] }],
      final_checks: ['open.ready']
    }
  }
});

function browserContext({ value = 'Smoke', attributes = {}, text = 'Fixture' } = {}) {
  const element = {
    value,
    disabled: false,
    readOnly: false,
    innerText: text,
    textContent: text,
    getBoundingClientRect: () => ({ width: 10, height: 10 }),
    getAttribute: name => Object.hasOwn(attributes, name) ? attributes[name] : null
  };
  const document = {
    body: { innerText: text },
    querySelectorAll: selector => selector === '#field' ? [element] : []
  };
  return { document, location: { href: 'https://fixture.test/' }, getComputedStyle: () => ({ display: 'block', visibility: 'visible' }) };
}

test('compiles every XRain case from pure JSON data', async () => {
  const source = JSON.parse(await readFile(new URL('./scenarios/xrain.json', import.meta.url), 'utf8'));
  for (const name of Object.keys(source.flows)) {
    const compiled = compileDeclarativeScenario(source, name);
    assert.ok(compiled.flow.steps.length > 0);
    assert.ok(Object.values(compiled.handlers).every(handler => typeof handler === 'function'));
  }
  const serialized = JSON.stringify(source);
  for (const forbidden of ['"handler"', '"expression"', '"script"', '"function"', '"eval"']) assert.equal(serialized.includes(forbidden), false, forbidden);
  const complex = compileDeclarativeScenario(source, 'complex');
  assert.equal(complex.flow.steps.find(step => step.id === 'select_email').action.method, 'chrome.evaluate', 'filtered click is generated by the compiler');
});

test('validates an unselected case before compilation returns', () => {
  const data = base({ type: 'page', text: { contains: 'Ready' } });
  data.flows.other = structuredClone(data.flows.simple);
  data.flows.other.flow_id = 'other';
  data.flows.other.steps[0].action = { type: 'ensure', value: 'unsupported' };
  assert.throws(() => compileDeclarativeScenario(data, 'simple'), { code: 'FLOW_INVALID' });
});

test('rejects executable hooks and fields from a predicate variant', () => {
  assert.throws(() => compileDeclarativeScenario(base({ type: 'page', expression: 'true' })), /FLOW_INVALID/);
  assert.throws(() => compileDeclarativeScenario(base({ type: 'all', conditions: [], value: { equals: 'x' } })), /FLOW_INVALID/);
});

test('rejects javascript navigation input while preserving ordinary URLs', () => {
  const scenario = base({ type: 'page', url: { equals: { input: 'url' } } }, { type: 'navigate', url: { input: 'url' }, wait_until: 'load' });
  assert.doesNotThrow(() => compileDeclarativeScenario(scenario));
  scenario.inputs.url = 'javascript:alert(1)';
  assert.throws(() => compileDeclarativeScenario(scenario), /javascript URLs/);
});

test('generated element predicates require one element and never expose values or body text', async () => {
  const scenario = base({ type: 'element', target: 'field', value: { equals: { input: 'expected' } } });
  const { handlers } = compileDeclarativeScenario(scenario);
  let expression;
  const result = await handlers['declarative.ready']({ inputs: scenario.inputs, evaluate: async value => {
    expression = value;
    return vm.runInNewContext(value, browserContext({ value: 'Smoke', text: 'secret page text' }));
  }});
  assert.equal(result.verdict, 'pass');
  assert.equal(result.actual.value, undefined);
  assert.equal(result.actual.text, undefined);
  assert.equal(result.actual.value_length, 5);
  assert.equal(JSON.stringify(result).includes('Smoke'), false);
  assert.equal(JSON.stringify(result).includes('secret page text'), false);
  assert.equal(expression.includes('Smoke'), true, 'the read expression may contain the resolved comparison, while evidence stays redacted');
});

test('missing attributes cannot satisfy an empty-string equality', () => {
  const expression = predicateExpression({ type: 'element', target: 'field', __selector: '#field', count: { equals: 1 }, attribute: { name: 'aria-selected', equals: '' } });
  const result = vm.runInNewContext(expression, browserContext({ attributes: {} }));
  assert.equal(result.verdict, 'fail');
  assert.equal(result.actual.attribute_present, false);
});
